services:
  app:
    build: ./backend
    container_name: todo-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
